### ISSUE TITLE
The whole thing crashes when a lot of predators is present and I add boid

### ISSUE THREAD

**Issue by andress-cz** [IshanManchanda/Boids#9]
Uncaught TypeError: Cannot read property 'position' of undefined
    at interaction (utils.js:49)
    at draw (sketch.js:30)
    at m.i.redraw (p5.min.js:3)
    at m.<anonymous> (p5.min.js:3)

I tried to figure out why, but I'm new to javascript and p5js so I could not :(

**Comment by IshanManchanda** [comment]
Thanks for alerting, I'll look into this.

**Comment by IshanManchanda** [comment]
This should hopefully be fixed in #10, will test and reopen if needed
